name: CI/CD

on: push

jobs:

  build:
    name: Build
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/michaeljohannesmeier/testhtml:latest
            ghcr.io/michaeljohannesmeier/testhtml:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    # if: github.ref == 'refs/heads/master'
    # needs: [ build ]
    runs-on: ubuntu-latest
    steps:


      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: 20.229.158.1
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create annotation for build error
        run: "ls -la $GITHUB_WORKSPACE/kubernetes/.kube"

      - name: Get kubectl version
        run: "kubectl --kubeconfig $GITHUB_WORKSPACE/kubernetes/.kube/config version"

      - name: Get kubectl version
        run: "scp -r -i $GITHUB_WORKSPACE/kubernetes/.kube/k8s-master_key.pem $GITHUB_WORKSPACE/kubernetes/matifests mj1020@20.229.158.1:/home/mj1020/apps/test"