name: CI/CD

on: push

jobs:

  build:
    name: Build
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/michaeljohannesmeier/testhtml:latest
            ghcr.io/michaeljohannesmeier/testhtml:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    # if: github.ref == 'refs/heads/master'
    # needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Decrypt files
        run: "pip install cryptography && python secrets.py decrypt ${{ secrets.DECRYPT_SECRET }}"

      - name: Set env variables
        run: "source kubernetes/connect/.env"

      - name: Get pods test
        run: "ssh -i kubernetes/connect/ssh_priv meiemi@20.31.219.238 kubectl get pods"

      - name: Copy manifests
        run: "scp -i kubernetes/connect/ssh_priv ./kubernetes/manifests/* meiemi@20.31.219.238:/home/meiemi/apps/test/"